### ISSUE TITLE
Google sheet for the ISO checklist

### ISSUE THREAD

**Issue by ngawangtrinley** [OpenPecha/MT-evaluation#1]
- [ ] Create a google sheet checklist for the ISO scorecards
- [ ] create a Google doc for each text that is analysed and highlight/mark each translation problem that will be referenced in the scorecard
- [ ] publish each scorecard on the forum

[ISO_5060_2024(en)-pages.pdf](https://github.com/user-attachments/files/16409107/ISO_5060_2024.en.-pages.pdf)

**Comment by wang1979** [comment]
[ISO-5060-F3--Non-Uniform scored table-mw31d3H16.xlsx](https://github.com/user-attachments/files/16438995/ISO-5060-F3--Non-Uniform.scored.table-mw31d3H16.xlsx)

I think there are some categories that don’t need to be counted as errors in machine learning, such as “style”, “Locale Conventions”, some other items also need include for Buddhism translation.

You can consult professional translators about deleting and adding evaluation items. Or you can decide yourself.

For the nonnessarry items, you can mark as zero in “Severity Levels & Severity Multiplier Values”

After that, I can translate this file into google sheet.
